## TRansforming data
> convert data into format required for analysis
1. Droppind data - drop variables or observations
2. Adding data - add vars or observations
3. sorting the data

In [1]:
import numpy as np, pandas as pd
from pandas import Series, DataFrame

In [ ]:
# arrange creates a list of values up to that num-1,
# reshape(rows, col) into form you want
df = DataFrame(np.arange(36).reshape(6,6))
df

    0   1   2   3   4   5
0   0   1   2   3   4   5
1   6   7   8   9  10  11
2  12  13  14  15  16  17
3  18  19  20  21  22  23
4  24  25  26  27  28  29
5  30  31  32  33  34  35

In [4]:

df2 = DataFrame(np.arange(15).reshape(5,3))
df2

    0   1   2
0   0   1   2
1   3   4   5
2   6   7   8
3   9  10  11
4  12  13  14

In [ ]:
# concat joins data from different sources into one data source
pd.concat([df, df2], axis =1)   # concatenat columns

    0   1   2   3   4   5     0     1     2
0   0   1   2   3   4   5   0.0   1.0   2.0
1   6   7   8   9  10  11   3.0   4.0   5.0
2  12  13  14  15  16  17   6.0   7.0   8.0
3  18  19  20  21  22  23   9.0  10.0  11.0
4  24  25  26  27  28  29  12.0  13.0  14.0
5  30  31  32  33  34  35   NaN   NaN   NaN

#### Dropping the data

In [8]:
df.drop([0, 2]) # put the index of the col/rows you want to drop

    0   1   2   3   4   5
1   6   7   8   9  10  11
3  18  19  20  21  22  23
4  24  25  26  27  28  29
5  30  31  32  33  34  35

#### Adding data

In [10]:
serie_obj = Series(np.arange(6))
serie_obj.name = 'musha lo'
serie_obj

0    0
1    1
2    2
3    3
4    4
5    5
Name: musha lo, dtype: int64

In [12]:
var_new = DataFrame.join(df, serie_obj)
var_new

    0   1   2   3   4   5  musha lo
0   0   1   2   3   4   5         0
1   6   7   8   9  10  11         1
2  12  13  14  15  16  17         2
3  18  19  20  21  22  23         3
4  24  25  26  27  28  29         4
5  30  31  32  33  34  35         5

In [ ]:
# add using concat
add_table = pd.concat([var_new, varb_new], ignore_index = False) # inore_index, indexes will now show and they will be dupes since they were independent
add_table

    0   1   2   3   4   5  musha lo
0   0   1   2   3   4   5         0
1   6   7   8   9  10  11         1
2  12  13  14  15  16  17         2
3  18  19  20  21  22  23         3
4  24  25  26  27  28  29         4
5  30  31  32  33  34  35         5
0   0   1   2   3   4   5         0
1   6   7   8   9  10  11         1
2  12  13  14  15  16  17         2
3  18  19  20  21  22  23         3
4  24  25  26  27  28  29         4
5  30  31  32  33  34  35         5

#### Sorting the data

In [17]:
df_sorted = df.sort_values(by=[5], ascending =False)
df_sorted

    0   1   2   3   4   5
5  30  31  32  33  34  35
4  24  25  26  27  28  29
3  18  19  20  21  22  23
2  12  13  14  15  16  17
1   6   7   8   9  10  11
0   0   1   2   3   4   5