In [1]:
import pandas as pd
import numpy as np

from pandas import DataFrame

In [ ]:
numsdf = DataFrame(np.arange(0, 90, 3).reshape(10, 3), index=['r1', 'r2','r3','r4','r5','r6','r7','r8','r9','r10'],columns=['col_one','col_two','col_three'])

In [10]:
numsdf

     col_one  col_two  col_three
r1         0        3          6
r2         9       12         15
r3        18       21         24
r4        27       30         33
r5        36       39         42
r6        45       48         17
r7        54       57         60
r8        63       66         69
r9        72       75         78
r10       81       84         87

In [20]:
# simple indexing, using iloc
numsdf.iloc[0,] # first 3 entries in r1

numsdf.iloc[1,1]

numsdf.iloc[5,2] = 17

In [ ]:
# get multiple rows and colums
# iloc[ rows, columns]
numsdf.iloc[[0,1,2], [0,1]]

    col_one  col_two
r1        0        3
r2        9       12
r3       18       21

In [23]:
# boolean indexing using comparison operators, basica math operations e.g > , == etc
mask = numsdf > 45
mask

# can also be used to retrieve a set of values, the same way we use it in R
numsdf[mask]

     col_one  col_two  col_three
r1       NaN      NaN        NaN
r2       NaN      NaN        NaN
r3       NaN      NaN        NaN
r4       NaN      NaN        NaN
r5       NaN      NaN        NaN
r6       NaN     48.0        NaN
r7      54.0     57.0       60.0
r8      63.0     66.0       69.0
r9      72.0     75.0       78.0
r10     81.0     84.0       87.0

In [25]:
# used to replace certain nums
numsdf[mask] = 1
numsdf

     col_one  col_two  col_three
r1         0        3          6
r2         9       12         15
r3        18       21         24
r4        27       30         33
r5        36       39         42
r6        45        1         17
r7         1        1          1
r8         1        1          1
r9         1        1          1
r10        1        1          1

In [ ]:
# now we are slciing buddy boy
#[startind:endindex], exclusive though
#[rows:rows, cols:cols]
numsdf.iloc[2:6, 1:3]

    col_two  col_three
r3       21         24
r4       30         33
r5       39         42
r6        1         17