## Missing values

- Approximating the missing values may be better than dropping entire rows or columns of missing information using:

1. *mean* approximation - from the values that we have we can get the mean and use that to approximate the missing values

### what this lesson covers
1. Discovering missing values
2. Fill in missing values
3. Counting missing values
4. Filtering out missing values

 here we learn how to treat missing values
 dataset with values 0, 99, or 9999 are considered as missing values

In [1]:
import numpy as np
import pandas as pd
from pandas import DataFrame

#### key methods for missing vals
- fillna()
- replace()
- interpolate() - uses some kind of interpolation technique to fill-values

In [3]:
# create dataset of people
data = {'Names': ['Sibonelo', 'Trust', 'Kamohelo', 'Rick', 'Morty', 'Goku', "Android 18"],
'Age': [20, 20, 19, 70, 14, 35, 30],
'Gender':["Male", 'Male', 'Male', 'Male', "Male", "Male", 'Female'],
'Rank':[2, 3, 1, 4, 5, 6, 7]}

In [4]:
# create dataframe
rank_df = pd.DataFrame(data)
rank_df

        Names  Age  Gender  Rank
0    Sibonelo   20    Male     2
1       Trust   20    Male     3
2    Kamohelo   19    Male     1
3        Rick   70    Male     4
4       Morty   14    Male     5
5        Goku   35    Male     6
6  Android 18   30  Female     7

In [6]:
rank_df.iloc[2:5, 1] = np.nan  # set entries in first column, to nan
rank_df.iloc[3,:] = np.nan
rank_df.iloc[3:6, 3] = np.nan

# print dataFRame with missing values
rank_df

        Names   Age  Gender  Rank
0    Sibonelo  20.0    Male   2.0
1       Trust  20.0    Male   3.0
2    Kamohelo   NaN    Male   1.0
3         NaN   NaN     NaN   NaN
4       Morty   NaN    Male   NaN
5        Goku  35.0    Male   NaN
6  Android 18  30.0  Female   7.0

##### functions to detect missing values
1. pd.isnull() -> return true for missing values in df
2. pd.notnull() -> true for values that are not misiing

In [7]:
rank_df.isnull()

   Names    Age  Gender   Rank
0  False  False   False  False
1  False  False   False  False
2  False   True   False  False
3   True   True    True   True
4  False   True   False   True
5  False  False   False   True
6  False  False   False  False

In [8]:
rank_df.notnull()

   Names    Age  Gender   Rank
0   True   True    True   True
1   True   True    True   True
2   True  False    True   True
3  False  False   False  False
4   True  False    True  False
5   True   True    True  False
6   True   True    True   True

In [ ]:
# apply boolean masking to show rows where values in age column are missing
missing_df = pd.isnull(rank_df['Age'])
rank_df[missing_df]

      Names  Age Gender  Rank
2  Kamohelo  NaN   Male   1.0
3       NaN  NaN    NaN   NaN
4     Morty  NaN   Male   NaN

In [12]:
# use fill-in functions
rank_df.fillna(9)

        Names   Age  Gender  Rank
0    Sibonelo  20.0    Male   2.0
1       Trust  20.0    Male   3.0
2    Kamohelo   9.0    Male   1.0
3           9   9.0       9   9.0
4       Morty   9.0    Male   9.0
5        Goku  35.0    Male   9.0
6  Android 18  30.0  Female   7.0

In [ ]:
# let's try to fill value with value in prev index
# forward-fill
rank_df.ffill()

# fill in with the next entry
# backward-fill
rank_df.bfill()

        Names   Age  Gender  Rank
0    Sibonelo  20.0    Male   2.0
1       Trust  20.0    Male   3.0
2    Kamohelo  35.0    Male   1.0
3       Morty  35.0    Male   7.0
4       Morty  35.0    Male   7.0
5        Goku  35.0    Male   7.0
6  Android 18  30.0  Female   7.0

In [22]:
# use linear interpolation, treats values as if they're equally spaces
# rank_df.interpolate(method = 'linear')

# did not work becuase I have some non-number values

In [ ]:
# use dropna() to remove all rows with na-values
rank_df.dropna()

        Names   Age  Gender  Rank
0    Sibonelo  20.0    Male   2.0
1       Trust  20.0    Male   3.0
6  Android 18  30.0  Female   7.0

In [ ]:
# drop rows with only missing values
rank_df.dropna(how='all')

# axis, what dimension do we wanna apply this accross?
# default is 0
# axis = 0 ---> ROWS
# axis = 1 ---> COLUMNS

        Names   Age  Gender  Rank
0    Sibonelo  20.0    Male   2.0
1       Trust  20.0    Male   3.0
2    Kamohelo   NaN    Male   1.0
4       Morty   NaN    Male   NaN
5        Goku  35.0    Male   NaN
6  Android 18  30.0  Female   7.0